export const INITIAL_LOAD_REQUEST = 'INITIAL_LOAD_REQUEST';
export const INITIAL_LOAD_SUCCESS = 'INITIAL_LOAD_SUCCESS';
export const INITIAL_LOAD_ERROR = 'INITIAL_LOAD_ERROR';

export const LOAD_MORE_REQUEST = 'LOAD_MORE_REQUEST';
export const LOAD_MORE_SUCCESS = 'LOAD_MORE_SUCCESS';
export const LOAD_MORE_ERROR = 'LOAD_MORE_ERROR';